# render.yaml - Finale, syntaktisch korrekte Version

services:
  - type: web
    name: ellies-tagebuch-bot-final  # Sie können diesen Namen bei Bedarf ändern
    
    # 'runtime: python' ist der Schlüssel, der die Python-spezifischen Felder aktiviert
    runtime: python
    plan: free
    
    # Python-Version, die für die Laufzeitumgebung verwendet werden soll
    pythonVersion: "3.11"

    # Befehl zum Installieren der Abhängigkeiten während der Build-Phase
    buildCommand: "pip install -r requirements.txt"
    
    # Befehl zum Starten der Anwendung nach einem erfolgreichen Build
    startCommand: "python main.py"

    # Systemabhängigkeiten, die VOR dem buildCommand installiert werden
    systemDependencies:
      - name: ffmpeg
      - name: libasound2-dev

    # Persistenter Speicher für die Datenbank
    disk:
      name: bot-database
      mountPath: /var/data/database
      sizeGB: 1

    # Umgebungsvariablen, die nicht geheim sind
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
