# render.yaml - Die alleinige Quelle der Wahrheit für unseren neuen Dienst

# Definiert alle Dienste, die zu unserem Projekt gehören
services:

  # 1. Der Web-Dienst für den Bot und die API
  - type: web
    # WICHTIG: Ein neuer, sauberer Name für den Dienst
    name: ellies-tagebuch-bot-final
    env: python
    plan: free
    
    # Wir erzwingen eine stabile Python-Version
    pythonVersion: "3.11"

    # Die Befehle zum Bauen und Starten
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"

    # Die entscheidenden System-Abhängigkeiten
    systemDependencies:
      - name: ffmpeg
      - name: libasound2-dev

    # Verknüpfung zum persistenten Speicher (siehe unten)
    # Der Name 'bot-database' muss mit dem Namen des pserv-Dienstes übereinstimmen
    disk:
      name: bot-database
      mountPath: /var/data/database
      sizeGB: 1 # Die kleinste Größe ist ausreichend

    # Umgebungsvariablen (nur die, die nicht geheim sind)
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1

  # 2. Ein separater, persistenter Speicher für die Datenbank
  - type: pserv
    name: bot-database # Dieser Name wird oben im 'disk'-Abschnitt referenziert
    plan: free
