# render.yaml - Version 6 (Syntaktisch korrekt)

services:
  - type: web
    name: ellies-tagebuch-bot-final
    env: python
    plan: free
    
    # Der 'build' Block enth채lt alles, was die Bau-Phase betrifft.
    # Dies ist die entscheidende Korrektur.
    build:
      # Befehl zum Installieren der Abh채ngigkeiten
      buildCommand: "pip install -r requirements.txt"
      # System-Abh채ngigkeiten, die VOR dem buildCommand installiert werden
      systemDependencies:
        - name: ffmpeg
        - name: libasound2-dev
    
    # Die Python-Version wird hier auf der obersten Ebene definiert.
    # Korrektur meiner vorherigen Annahme. Die Doku zeigt sie hier.
    pythonVersion: "3.11"

    # Der Befehl zum Starten der Anwendung NACH dem Bauen
    startCommand: "python main.py"

    # Persistenter Speicher f체r die Datenbank
    disk:
      name: bot-database
      mountPath: /var/data/database
      sizeGB: 1

    # Umgebungsvariablen
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
