# render.yaml - Korrigiert mit dem exakten Dienstnamen

services:
  - type: web
    # HIER IST DIE WICHTIGE ÄNDERUNG:
    name: tleick88-tleick88-ElliesTagebuchBot2 
    env: python
    plan: free
    
    # Legt die Python-Version fest. Eine stabile Version ist oft besser.
    pythonVersion: "3.11"

    # Befehle zum Bauen und Starten
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"

    # Systemabhängigkeiten, die vor dem Build installiert werden.
    # Dies ist der wichtigste Teil für die Audioverarbeitung.
    systemDependencies:
      - name: ffmpeg
      - name: libasound2-dev # Wichtige Bibliothek für Audio I/O unter Linux

    # Umgebungsvariablen
    envVars:
      - key: PYTHONUNBUFFERED # Sorgt für bessere Logs
        value: 1
